stages:
  split:
    cmd: python src/data/split_data.py
    deps:
      - data/raw/raw.csv
      - src/data/split_data.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - src/data/normalize_data.py
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - src/models/grid_search.py
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/models/train_model.py
    deps:
      - models/best_params.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - src/models/train_model.py
    outs:
      - models/gbr_model.pkl



  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - models/gbr_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - src/models/evaluate_model.py
    outs:
      - data/prediction.csv
      - metrics/scores.json
